# Site settings
title: M1s0n's Blog
smalltalk: "知识面决定攻击面，知识链决定杀伤链"
description: > 
baseurl: "/" 
paginate: 5
url: "https://github.com/m1n0s-sec"
github_username: m1n0s-sec  
portfolio_url: 

# Build settings
markdown: kramdown
