title: M1n0s
email: 
author:
  picture: https://files.catbox.moe/1e7no4.jpg #URL FORMAT
  name: M1n0s
  location: CN
  description: "我相信指尖有改变世界的力量"  
description: 知识面决定攻击面，知识链决定杀伤链
baseurl: "/"
url: https://github.com/m1n0s-secx
github_username:  m1n0s-sec
github_url: https://github.com/m1n0s-sec

# Build settings
permalink: :title
paginate: 1
paginate_path: "page:num"
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
